In [3]:
import numpy as np


In [4]:
print(np.zeros((5)))

[0. 0. 0. 0. 0.]


In [5]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [6]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [8]:
print(5*np.ones((3,5)))

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [9]:
np.empty((3,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [10]:
np.empty((2,3))

array([[4.66764279e-310, 0.00000000e+000, 6.93839802e-310],
       [6.93839616e-310, 6.93837406e-310, 6.93839812e-310]])

In [11]:
mat1=np.eye(4)
print(mat1.shape)

(4, 4)


In [12]:
print(mat1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
print(np.random.rand(2,3))

[[0.55452723 0.91147709 0.59760979]
 [0.47677589 0.38854326 0.58957771]]


In [14]:
print(np.random.randn(2,3))

[[ 0.41621248 -0.12024226  0.46256413]
 [ 0.55344378  0.50591329 -0.37567156]]


In [15]:
print(np.random.randint(1,100,5))

[31 36 31 75 35]


In [16]:
print(np.random.randint(1,100,(4,4)))

[[62 16 65 98]
 [50 14 80 52]
 [27 21 25 11]
 [86 33 85 52]]


In [17]:
###############################################
from numpy.random import randint as ri
a=ri(1,100,30)
b=a.reshape(2,3,5)
c=a.reshape(6,5)
print(a.shape)
print(b.shape)
print(c.shape)

(30,)
(2, 3, 5)
(6, 5)


In [18]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


a looks like
 -------------------- 
 [22 29 38 39 56 83 27 20 13 23 39 95 42  4 37 52 21 85 35 76 54 96 43 41
 81 51 92  5 75 13] 
 --------------------

b looks like
 -------------------- 
 [[[22 29 38 39 56]
  [83 27 20 13 23]
  [39 95 42  4 37]]

 [[52 21 85 35 76]
  [54 96 43 41 81]
  [51 92  5 75 13]]] 
 --------------------

c looks like
 -------------------- 
 [[22 29 38 39 56]
 [83 27 20 13 23]
 [39 95 42  4 37]
 [52 21 85 35 76]
 [54 96 43 41 81]
 [51 92  5 75 13]] 
 --------------------


In [19]:
A=ri(1,100,10)
print(A)

[94 28 56  4 31 74 35 53 90 78]


In [20]:
print(np.sort(A,kind='mergesort'))

[ 4 28 31 35 53 56 74 78 90 94]


In [21]:
M=ri(1,100,25).reshape(5,5)
print(M)
print('\n',np.sort(M,kind="mergesort"))
print('\n',np.sort(M,axis=0,kind="mergesort"))

[[24 33 80 34 36]
 [74 32 67 99 22]
 [15 70 69 96 22]
 [61 89 30 35 24]
 [26 20 67 60  4]]

 [[24 33 34 36 80]
 [22 32 67 74 99]
 [15 22 69 70 96]
 [24 30 35 61 89]
 [ 4 20 26 60 67]]

 [[15 20 30 34  4]
 [24 32 67 35 22]
 [26 33 67 60 22]
 [61 70 69 96 24]
 [74 89 80 99 36]]


In [22]:
print(A.max())
print(M.max())


94
99


In [23]:
mat2=ri(1,10,(1,3,3)).reshape(3,3)

In [24]:
print(mat2)

[[7 1 2]
 [4 5 1]
 [4 8 1]]


In [25]:
print(mat2.diagonal(0))

[7 5 1]


In [26]:
for i in range(3):
    for j in range(3):
        if(i==j):
            print(mat2[i][j])
            

7
5
1


In [27]:
for i in range(3):
    for j in range(3):
        if(i+j==2):
            print(mat2[i][j])
            

2
5
4


In [28]:
mat2[0:9:3]

array([[7, 1, 2]])